services:
  - type: web
    name: rag-assistant
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd RAG-assistance && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.10"
